-- SQL dump generated using DBML (dbml.dbdiagram.io)
-- Database: PostgreSQL
-- Generated at: 2026-10-08T23:55:33.281Z

CREATE TYPE "user_role" AS ENUM (
  'USER',
  'MANAGER',
  'ADMIN'
);

CREATE TYPE "invite_response" AS ENUM (
  'PENDING',
  'ACCEPTED',
  'DECLINED'
);

CREATE TABLE "events" (
  "event_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "event_name" varchar(255) NOT NULL,
  "event_desc" text NOT NULL,
  "location_id" integer NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "starts_on" timestamp NOT NULL,
  "creator_id" integer NOT NULL
);

CREATE TABLE "users" (
  "user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(255) UNIQUE NOT NULL,
  "role" user_role NOT NULL DEFAULT (USER),
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "manager_event" (
  "event_id" integer NOT NULL,
  "manager_id" integer NOT NULL,
  PRIMARY KEY ("event_id", "manager_id")
);

CREATE TABLE "archived_events" (
  "arc_event_id" integer PRIMARY KEY,
  "arc_event_name" varchar(255),
  "arc_event_date" timestamp,
  "arc_event_size" integer,
  "arc_event_desc" varchar(255),
  "arc_event_loc" varchar(255),
  "happened_on" timestamp
);

CREATE TABLE "invites" (
  "event_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "status" invite_response NOT NULL DEFAULT 'PENDING',
  "message" text,
  "invited_at" timestamp NOT NULL DEFAULT (now()),
  "responded_at" timestamp,
  PRIMARY KEY ("event_id", "user_id")
);

CREATE TABLE "locations" (
  "location_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "location_name" varchar(255),
  "address" varchar(255) NOT NULL,
  "location_desc" text,
  "creator_id" integer NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE INDEX "event_invite_index" ON "invites" ("event_id");

CREATE INDEX "user_invite_index" ON "invites" ("user_id");

COMMENT ON COLUMN "locations"."location_desc" IS 'Basic Description, holds navigation tips and or building info';

COMMENT ON COLUMN "locations"."creator_id" IS 'Most of the time, this will be an admin or a defacto "System" account, such as user 0';

ALTER TABLE "events" ADD FOREIGN KEY ("creator_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "events" ADD FOREIGN KEY ("location_id") REFERENCES "locations" ("location_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "manager_event" ADD FOREIGN KEY ("event_id") REFERENCES "events" ("event_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "manager_event" ADD FOREIGN KEY ("manager_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "invites" ADD FOREIGN KEY ("event_id") REFERENCES "events" ("event_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "invites" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "locations" ADD FOREIGN KEY ("creator_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

-- Defer constraint checking for INSERT
BEGIN;
SET CONSTRAINTS ALL DEFERRED;

INSERT INTO "users" ("user_id", "username", "role", "created_at", "updated_at")
VALUES
  (0, 'system', 'ADMIN', 'now()', 'now()'),
  (NULL, 'admin_demo_1', 'ADMIN', '2026-10-07 21:27:35.759411', '2026-10-07 21:27:35.759411'),
  (NULL, 'admin_demo_2', 'ADMIN', '2026-10-07 21:27:35.759411', '2026-10-07 21:27:35.759411'),
  (NULL, 'manager_demo_1', 'MANAGER', '2026-10-07 21:27:35.759411', '2026-10-07 21:27:35.759411'),
  (NULL, 'manager_demo_2', 'MANAGER', '2026-10-07 21:27:35.759411', '2026-10-07 21:27:35.759411'),
  (NULL, 'manager_demo_3', 'MANAGER', '2026-10-07 21:27:35.759411', '2026-10-07 21:27:35.759411'),
  (NULL, 'ann_demo', 'USER', '2026-10-07 21:27:35.759411', '2026-10-07 21:27:35.759411'),
  (NULL, 'sarah_demo', 'USER', '2026-10-07 21:27:35.759411', '2026-10-07 21:27:35.759411'),
  (NULL, 'paul_demo', 'USER', '2026-10-07 21:27:35.759411', '2026-10-07 21:27:35.759411'),
  (NULL, 'billy_demo', 'USER', '2026-10-07 21:27:35.759411', '2026-10-07 21:27:35.759411');
INSERT INTO "locations" ("location_name", "address", "location_desc", "created_at", "updated_at", "creator_id")
VALUES
  ('Student Center', 'CSUMB Campus', 'Main student gathering space', '2026-10-07 21:24:05.619425', '2026-10-07 21:24:05.619425', 0),
  ('University Library', 'CSUMB Campus', 'Quiet indoor event location', '2026-10-07 21:24:05.619425', '2026-10-07 21:24:05.619425', 0),
  ('Outdoor Amphitheater', 'CSUMB Campus', 'Outdoor event space', '2026-10-07 21:24:05.619425', '2026-10-07 21:24:05.619425', 0),
  ('Monterey Bay Aquarium', 'Monterey, CA', 'Large indoor venue', '2026-10-07 21:24:05.619425', '2026-10-07 21:24:05.619425', 0),
  ('Downtown Monterey', 'Monterey, CA', 'Central community event area', '2026-10-07 21:24:05.619425', '2026-10-07 21:24:05.619425', 0),
  ('Carmel Beach', 'Carmel-by-the-Sea, CA', 'Outdoor beach location', '2026-10-07 21:24:05.619425', '2026-10-07 21:24:05.619425', 0),
  ('Salinas Community Center', 'Salinas, CA', 'Indoor community venue', '2026-10-07 21:24:05.619425', '2026-10-07 21:24:05.619425', 0),
  ('Seaside Conference Center', 'Seaside, CA', 'Conference and meeting space', '2026-10-07 21:24:05.619425', '2026-10-07 21:24:05.619425', 0),
  ('Pacific Grove Recreation Center', 'Pacific Grove, CA', 'Indoor recreation venue', '2026-10-07 21:24:05.619425', '2026-10-07 21:24:05.619425', 0);
INSERT INTO "events" ("event_name", "event_desc", "starts_on", "creator_id", "created_at", "updated_at", "location_id")
VALUES
  ('Community Game Night', 'An evening of board games and snacks.', '2026-11-15T18:00:00', 3, '2026-10-07 21:33:37.859388', '2026-10-07 21:33:37.859388', 1),
  ('Beach Cleanup', 'A community cleanup and conservation event.', '2026-12-05T09:00:00', 4, '2026-10-07 21:33:37.859388', '2026-10-07 21:33:37.859388', 6);
INSERT INTO "invites" ("user_id", "event_id", "status", "invited_at", "responded_at")
VALUES
  (6, 1, 'ACCEPTED', '2026-10-07 21:44:13.778439', '2026-10-08T10:00:00'),
  (7, 1, 'ACCEPTED', '2026-10-07 21:44:13.778439', '2026-10-08T11:30:00'),
  (8, 1, 'DECLINED', '2026-10-07 21:44:13.778439', '2026-10-08T12:00:00'),
  (9, 1, 'PENDING', '2026-10-07 21:44:13.778439', NULL),
  (6, 2, 'ACCEPTED', '2026-10-07 21:44:13.778439', '2026-10-09T09:00:00'),
  (7, 2, 'DECLINED', '2026-10-07 21:44:13.778439', '2026-10-09T10:15:00'),
  (8, 2, 'PENDING', '2026-10-07 21:44:13.778439', NULL);

SET CONSTRAINTS ALL IMMEDIATE;
COMMIT;